"""Create ticket types table

Revision ID: 3fe3a8c6bcd7
Revises: 140a9908ad8d
Create Date: 2026-07-22 15:38:17.652309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe3a8c6bcd7'
down_revision = '140a9908ad8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sold_quantity', sa.Integer(), nullable=False),
    sa.Column('max_per_order', sa.Integer(), nullable=False),
    sa.Column('sales_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_ticket_type_price_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_ticket_type_quantity_positive'),
    sa.CheckConstraint('sold_quantity <= quantity', name='ck_ticket_type_sold_within_quantity'),
    sa.CheckConstraint('sold_quantity >= 0', name='ck_ticket_type_sold_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='uq_ticket_type_event_name')
    )
    with op.batch_alter_table('ticket_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_types_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_types_event_id'))

    op.drop_table('ticket_types')
    # ### end Alembic commands ###
