"""Create bookings table

Revision ID: 78da3349f5c3
Revises: 3fe3a8c6bcd7
Create Date: 2026-07-22 15:49:41.694050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78da3349f5c3'
down_revision = '3fe3a8c6bcd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('booking_reference', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_booking_quantity_positive'),
    sa.CheckConstraint('total_amount >= 0', name='ck_booking_total_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_booking_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_reference'), ['booking_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_ticket_type_id'), ['ticket_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_ticket_type_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_event_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_reference'))

    op.drop_table('bookings')
    # ### end Alembic commands ###
